name: OWASP ZAP Integration with GitHub Actions

on:
  push:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # optional but good for full history

      - name: Run ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
